Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
	  v.cpus = 2
  end

  vm_box = "ubuntu/xenial64"
  config.vm.define "webapp" do |webapp|
    webapp.vm.box = vm_box
    webapp.vm.hostname = 'ubuntu-xenial-webapp'
    webapp.vm.network "private_network", ip: "192.168.56.100"
	webapp.vm.provision :shell, path: "bootstrap.sh"
  end
end