apiVersion: apps/v1
kind: Deployment
  metadata:
      name: nginx-prod
      labels:
          app: nginx-prod
spec:
  replicas: 3
  selector:
      matchLabels:
          app: nginx-prod
  template:
      metadata:
          labels:
              app: nginx-prod
  spec:
      containers:
      - name: nginx-prod
      image: nginx
      ports:
      - containerPort: 80